language: node_js

node_js:
- node

before_script:
- npm install

script: npm test && npm run lint && npm run generate

before_deploy:
- zip -r dgds-ui.zip dist/*

deploy:
  provider: releases
  api_key:
    secure: d7UVmk+WzPl0t/b+N50YYQi0DbnCRQQrB4JoJTbHMDShpXta7zSX0xy/VFu3LgBc4Wlw9Sdn/asaiCfOK4Zidn8E6idVuDlGM9bR8V3gZwMKg0u9cJai9VpGAIb1l6AQ8E5eYd4X/WzVVbRQ6ZeWcVrmCAuB30u9KtqJCF0fbRdWGZgNDDpYW+yPya6pNwpKCk8lLscBfwAHNFeZUDgPMgDfcfeGs08GP2oVQZIYm/BUrGKJl9mEM2HI49vw/7BYqyo3GH/IYGy2sjhgo30UzI/dHnjwrRjbZcblV4+bcZ4MZnRa/D3Zzr3lB5Z9ZdpVBSVJMBgEwUvnuzb1n1Q5SuKHQABtX/kAm9F5LMkNj8q3DcFu0inf3m1d03QToNCjVKF7co1MzIAgtjN2R0I2yvXLAEuUBuAX9aGIF/ubTm/V1ESE7/rKxTLJBqb36Z8hK353zykAZF1W56H8PHIqW7gwYHhRGuLUmM3qOTwV8FN4Ff8S80y9BCkIZ8iJ7gMD8V/Prv4o2pYJPNpGjFatR8x8tUQ2PUHWfu05li30C9/y5ATg7hOwzEpkxFd4L9AmG2o06j/urrokWGMEG0sVB4d88LM9eScsVAoi7LS3a/z8QyqRQ1ghcLVnNPNESNVU17XvdGwcagbNderwA6TRGua8yJjuJO+lWw/1wVniE5o=
  overwrite: true
  skip_cleanup: true
  file: dgds-ui.zip
  on:
    tags: true
    repo: openearth/dgds-front-end
    branch: master
